"""Writes CREDITS.md from src/data/image-credits.json plus the fixed list of generated assets.
Usage: python3 scripts/credits.py
"""
import html, json, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IMAGES = json.load(open(os.path.join(ROOT, "src", "data", "image-credits.json")))
VOICE = json.load(open(os.path.join(ROOT, "src", "data", "voice.json")))
HALFTONE = [g["name"] for g in json.load(open(os.path.join(ROOT, "src", "data", "halftone.json")))]

USE = {
    "gandhi": "Stamp portrait (scene 4)",
    "nehru": "Stamp portrait (scene 4)",
    "jinnah": "Stamp portrait (scene 4)",
    "mountbatten": "Stamp portrait (scene 4)",
}


def text(s):
    s = re.sub(r"<[^>]+>", " ", s or "")
    s = html.unescape(re.sub(r"\s+", " ", s)).strip()
    # Commons often repeats the author in a hidden span, e.g. "Anonymous Unknown author".
    return s[:160]


def main():
    out = ["# Credits", "",
           "Every image and sound in `public/` is listed here with its source and license.", "",
           "## Images (Wikimedia Commons)", "",
           "| File | Used for | Source | Author | License |", "|---|---|---|---|---|"]
    for key, m in IMAGES.items():
        if key in USE:
            use = USE[key]
            files = f"`images/originals/{key}.jpg`, `images/cutouts/{key}.png`, `images/stamps/{key}-duotone.png`"
        elif key in HALFTONE:
            use = "Gold halftone through the torn map (scene 6)"
            files = f"`images/originals/{key}.jpg`"
        else:
            continue
        out.append(f"| {files} | {use} | [{m['title']}]({m['page']}) | {text(m['artist']) or 'Unknown'} | {m['license']} |")
    out += ["",
            "Portrait cutouts were made with [rembg](https://github.com/danielgatis/rembg) "
            "(`isnet-general-use`; `u2net_human_seg` for Gandhi). The originals are kept next to the cutouts. "
            "Duotones and halftones were generated by `scripts/cutouts.py` and `scripts/halftone.py`.", "",
            "If you swap a photo, re-run `npm run assets` and `python3 scripts/credits.py`.", "",
            "## Map data", "",
            "| File | Source | License |", "|---|---|---|",
            "| `src/data/map.json` | [Natural Earth](https://www.naturalearthdata.com/) 1:50m admin-0 countries, via the "
            "[world-atlas](https://github.com/topojson/world-atlas) npm package; projected by `scripts/build-map.mjs` | Public domain |", "",
            "Borders are simplified for a classroom overview. The western line is drawn only south of Jammu and Kashmir.", "",
            "## Fonts", "",
            "| File | Source | License |", "|---|---|---|",
            "| `fonts/Archivo-ExtraBold-latin.woff2` | [Archivo](https://fonts.google.com/specimen/Archivo) (Google Fonts) | SIL Open Font License 1.1 |",
            "| `fonts/Caveat-latin.woff2` | [Caveat](https://fonts.google.com/specimen/Caveat) (Google Fonts) | SIL Open Font License 1.1 |", "",
            "## Narration", "",
            "Generated with [ElevenLabs](https://elevenlabs.io) text-to-speech from `narration.txt`, using two voices made with "
            "ElevenLabs Voice Design for this project (Nisha, and a calm adult narrator). Output is owned by the account holder "
            "under ElevenLabs' terms. Replace any file with your own recording of the same name, then run "
            "`python3 scripts/voice.py --durations`.", "",
            "| File | Voice | Line |", "|---|---|---|"]
    for cid, v in VOICE.items():
        out.append(f"| `{v['file']}` | {v['voice'].title()} | {v['text']} |")
    out += ["", "## Music and sound effects", "",
            "All synthesized for this project by `scripts/synth-audio.py` (NumPy/SciPy sine waves and filtered noise). "
            "Released as CC0. Pixabay Music was not reachable from the build environment, and Freesound downloads need "
            "a logged-in account, so nothing was downloaded.", "",
            "| File | What it is | License |", "|---|---|---|"]
    audio = [
        ("audio/music/tanpura-drone.mp3", "Tanpura-style drone on D (Sa–Pa), with a soft Sa–Pa pad"),
        ("audio/music/low-swell.mp3", "Low swell under the border scene"),
        ("audio/sfx/crickets.mp3", "Crickets at night"),
        ("audio/sfx/pen-scratch-1.mp3 … pen-scratch-3.wav", "Pen scratching on paper"),
        ("audio/sfx/lamp-flicker.mp3", "Oil-lamp flutter"),
        ("audio/sfx/paper-slide.mp3", "Diary page sliding in"),
        ("audio/sfx/stamp-thud.mp3", "Rubber stamp"),
        ("audio/sfx/drum-hit.mp3", "Single low drum hit"),
        ("audio/sfx/train-whistle.mp3", "Steam-train whistle"),
        ("audio/sfx/train-wheels.mp3", "Train wheels over rail joints"),
        ("audio/sfx/crowd-murmur.mp3", "Distant crowd murmur"),
        ("audio/sfx/book-close.mp3", "Diary closing"),
    ]
    for f, what in audio:
        out.append(f"| `{f}` | {what} | CC0 (original) |")
    out += ["", "## Textures", "",
            "`images/textures/paper.png` and `images/textures/grain-*.png` were generated by `scripts/make-textures.py` (CC0, original).", ""]
    open(os.path.join(ROOT, "CREDITS.md"), "w").write("\n".join(out))
    print("CREDITS.md written")


if __name__ == "__main__":
    main()
